# 物华弥新 - 器者名称 & 卡池名称词库
# 器者名称按职业分组，每行一个名字直接回车即可

characters:
  轻锐:
    特出: |
      兔形陶埙
      四龙四凤座
      越王勾践剑
      金瓯永固杯
      上阳台贴
      雪景寒林图
      铜车马
      亚长牛尊
      鹿王本生图
      酒帐
      水晶杯
      海错图
      赤壁赋页
      卷云金喇叭
      秋操杯
    优异: |
      制盐砖
      天亡簋
      扯淡碑
      少虡剑
      样式雷
      七盘舞砖
      鎏金银壶
      商鞅方升
      夜行铜牌
      战国铜冰鉴
    新生: |
      蛙锣
      蒙医药袋
      宝石冠
      驿使图砖

  远击:
    特出: |
      云雷纹大铙
      宋金项饰
      金蝉玉叶
      狸猫盘
      愿望杯
      彩凤鸣岐
      青铜仙鹤
      麟趾马蹄金
      万工轿
      三兔藻井
      星月夜
      天球仪
      小宋香炉
      金冠带
      桃源仙境图
    优异: |
      粉白双耳瓶
      大神龛
      万国全图
      茶叶生产画
      鹿角立鹤
      自来火二号
      格萨尔唐卡
      外销壁纸
      克拉克瓷
      针铺铜版
      跪射俑
    新生: |
      山水人物镜
      心形枪
      可爱花束
  宿卫:
    特出: |
      鎏金骑士
      铜奔马
      毛公鼎
      曾侯乙编钟
      溪山行旅图
      铜坐龙
      午门
      微缩家居
      真珠宝幢
      青瓷莲花尊
      天王石刻
    优异: |
      妇好鸮尊
      吴王夫差矛
      阴山岩画
      大盂鼎
      宴猎攻战壶
      琉璃塔拱门
    新生: |
      白釉绿彩瓶
      人头瓶
      战国铜餐具
      玛雅陶碗
  构术:
    特出: |
      芙蓉炉
      贾湖骨笛
      白石散乐
      洛神赋图
      千里江山图
      银香囊
      T形帛画
      断臂维纳斯
      五弦琵琶
      莫高窟220
      秦公镈
      铜壶滴漏
      莫高窟记
      百花卷图
      素纱单衣
      王氏书翰卷
      睡莲
      金石录
      万壑松风图
    优异: |
      蝠桃瓶
      天蓝瓶
      玉琮王
      长信宫灯
      聊斋图说
      商周铜人
    新生: |
      鹦鹉银罐
      龙纹陶盘
      冷暖自知印
      天气卜骨
  战略:
    特出: |
      利簋
      五星出东方
      莲塘乳鸭图
      十二花卉杯
      鸟音山水钟
      商周十供
      海水江崖炉
      敦煌飞天
      银雀山汉简
      向日葵
      浑天仪
      太阳神鸟
      广彩描金壶
      庞贝
    优异: |
      晋侯鸟尊
      白龙梅瓶
      丙午神钩
      诗文执壶
      皇后之玺
    新生: |
      舞蹈陶盘
      果树双管瓶
      五柱器

banners:
  # 1.0
  金碧流彩: 金瓯永固杯
  宴席之乐: 狸猫盘
  # 1.1
  一见神思: 洛神赋图
  月令花时: 十二花卉杯
  千载青绿: 千里江山图
  歆铭长愿: 毛公鼎
  # 1.2
  暗香盈袖: 银香囊
  山高水长: 上阳台帖
  仙人入梦: T形帛画
  千乘之国: 四龙四凤座
  # 1.3
  雪蓑风笠: 雪景寒林图
  万山旅人: 溪山行旅图
  杳杳钟声: 鸟音山水钟
  十年一剑: 越王勾践剑
  # 1.4
  北风守望: 愿望杯
  与美并行: 断臂维纳斯
  丝弦故梦: 五弦琵琶
  天时地利: 五星出东方
  # 1.5
  灵琴问梦: 彩凤鸣岐
  莲台旋舞: 莫高窟220
  思无邪: 商周十供
  # 1.6
  镈音奏秦: 秦公镈
  策马长驱: 铜车马
  乐彼之园: 青铜仙鹤
  金声玉振: 曾侯乙编钟
  # 1.7
  云起龙腾: 铜坐龙
  猗猗嘉禾: 亚长牛尊
  # 1.8
  漏箭浮生: 铜壶滴漏
  良金瑞灵: 麟趾马蹄金
  浩浩汤汤: 海水江崖炉
  # 1.9
  朱金彩绣: 万工轿
  能工巧匠: 微缩家具
  呦呦鹿鸣: 鹿王本生图
  # 2.0
  此待君归: 酒帐
  山止川行: 莫高窟记
  水中有兔: 三兔藻井
  飒沓流星: 铜奔马
  # 2.1
  花开四时: 百花图卷
  水玉冰心: 水晶杯
  轻绡婆娑: 素纱单衣
  # 2.2
  塔中闻愿: 真珠宝幢
  纵横无间: 银雀山汉简
  如君执笔: 王氏书翰卷
  # 2.3
  今夜晨星: 星月夜
  无尽轮回: 向日葵
  池中印象: 睡莲
  # 2.4
  四海无争: 天球仪
  海纳百川: 海错图
  # 2.5
  瓷生莲心: 青瓷莲花尊
  刻名存念: 小宋香炉
  # 2.6
  千古风流: 赤壁赋页
  录此平生: 金石录
  # 2.7
  寸中宇宙: 太阳神鸟
  祥云飞旋: 卷云金喇叭
  # 3.0
  青山见我: 万壑松风图
  镇宅守界: 天王石刻
  # 3.1
  新荷跳雨: 秋操杯
  境中阡陌: 桃源仙境图
  # 3.2
  艺格敷词: 庞贝
  粉雕玉琢: 芙蓉炉